### ISSUE TITLE
Question: Is 4.5 really the minimum node version supported?

### ISSUE THREAD

**Issue by ajones-miovision** [Shadowblazen/dynamodb-wrapper#1]
The AWS Lambda node runtime is 4.3.2. The package.json on this module has 4.5 as the minimum node runtime. Is there something being used that is only available on 4.5 (i.e. will this module fail if run via a lambda)?

**Comment by Shadowblazen** [comment]
To my knowledge, there's nothing particularly special about node 4.5. The only reason that's listed in the package.json is because that was the latest version in the 4.x series at the time I first published the module. That's the earliest version I began testing with, and I wanted to give some indication as to what was supported.

This module is written in TypeScript and compiled down to ES6, so it uses many ES6 constructs such as classes, generators, etc. I haven't yet done thorough research & testing to determine with confidence the minimum version of node required to support the various ES6 features that this module uses.

A few minutes ago, I was able to install node 4.3.2 on my Macbook and use the core features of this module successfully. So - this is only anecdotal evidence at this point - but I believe it should work on lambda.

I would want to do more thorough research & testing before updating the official claim in my package.json file though. If that's something you'd value, I will consider it a feature request and might take on that task in the near future.

If you're willing to share, I'm curious to hear a little bit about your use case. What sort of workload were you considering using this module in lambda for?

**Comment by ajones-miovision** [comment]
We publish about 15 million records a day to dynamo via AWS IoT -> Kinesis Streams -> Lambda -> Dynamo. We currently do batch write operations but our data can be bursty at times so we may be running at about 40% WCU and then suddenly spike above 100%. Even with auto scaling the WCU's we have found that our spikes are large enough that auto scaling can't seem to keep up. We've tried exponential backoff reties with limited success in the past but wanted to give your library a try as it is a more complete and feature rich library than our initial (and very basic) wrapper is. The big issue we face is that we want to do batch writing, but if a single item in the batch doesn't insert successfully, then we fail the lambda and it must retry the batch. We have found that the unprocessed records that the aws sdk returns you on failure always seem to be one less then the previous retry, no matter what our WCU. For example, if we try to insert 50, let's say the first 25 go in successfully, but the second batch write of 25 failed, the unprocessed records would always have 24 items in it. We would do a backoff and retry the 24 and we would receive 23 unprocessed records. Backoff and then 22 unprocessed records, etc. 

Anyway, I have deploy our lambda with you library to our staging environment and it seems to function without any noticeable node errors so that's a plus :).
Last night I tried to insert a batch of 8 into a dynamo table with a WCU of 2. You library did retry with an exponential backoff as expected, but after six retries all 8 had still not successfully landed. That was kind of a weak test since i didn't take into table sharding and hot keys so I'm going to try to set up a better test scenario.

**Comment by ajones-miovision** [comment]
Actually, we only have one writer process (lambda) so exponential backoff gains us nothing. In fact, we can basically just continuously retry unprocessed items in small batches and eventually they should all get through.

**Comment by Shadowblazen** [comment]
Yeah, your description of unprocessed records is consistent with the [AWS BatchWriteItem documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html).

> Note that if _none_ of the items can be processed due to insufficient provisioned throughput on all of the tables in the request, then BatchWriteItem will return a ProvisionedThroughputExceededException.

So if you attempt to batch write 25 items with the aws-sdk, and all 25 fail, instead of getting an HTTP 200 response with 25 UnprocessedItems, you would instead receive an HTTP 400 response with code = ProvisionedThroughputExceededException (and no UnprocessedItems). This DynamoDBWrapper library is also intended to behave the same way as the aws-sdk in this regard.

Thanks for sharing. Hopefully in your case, a pattern emerges where the spikes tend occur on predictable days or during predictable hours. If so, preemptively increasing throughput by predicting usage patterns could be a useful replacement for (or in addition to) reactive auto-scaling.

**Comment by Shadowblazen** [comment]
As of DynamoDBWrapper v1.4.0, I've now marked the required version of node as >=4.0.0
